import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f4f4f2",
        "on-tertiary-fixed": "#081b3b",
        "on-secondary-fixed-variant": "#474746",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        tertiary: "#4e5e82",
        "inverse-primary": "#e4c285",
        "on-surface": "#1a1c1b",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#b6c6ef",
        "secondary-container": "#e2dfde",
        "on-background": "#1a1c1b",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#e4c285",
        "outline-variant": "#d0c5b5",
        "inverse-on-surface": "#f1f1ef",
        "tertiary-container": "#9dadd5",
        "surface-container": "#eeeeec",
        surface: "#f9f9f7",
        "on-tertiary-container": "#314163",
        "surface-tint": "#745a27",
        "on-tertiary-fixed-variant": "#374669",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#f9f9f7",
        primary: "#745a27",
        secondary: "#5f5e5e",
        "primary-container": "#c9a96e",
        "on-primary-fixed": "#261900",
        "surface-variant": "#e2e3e1",
        "on-primary-fixed-variant": "#5a4312",
        "on-error-container": "#93000a",
        outline: "#7f7668",
        "on-secondary-container": "#636262",
        "on-primary-container": "#543d0c",
        "inverse-surface": "#2f3130",
        "primary-fixed": "#ffdea4",
        "on-surface-variant": "#4d463a",
        "surface-container-highest": "#e2e3e1",
        "surface-dim": "#dadad8",
        "surface-container-high": "#e8e8e6",
        "on-error": "#ffffff",
        background: "#f9f9f7",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "Georgia", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        notoSerif: ["Noto Serif", "Georgia", "serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        marquee: "marquee 25s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
